# generated by Gemini 3 Pro
import numpy as np
import soundfile as sf
from scipy import signal
import math
import os
import sys
import time
import random

from sfumato import settings
from sfumato.transmitter import FmTransmitter
from sfumato.reciever import FmReceiver
from sfumato.utils.output_audio import save_audio


# ==========================================
# 🎨 Radio UI System
# ==========================================
class RadioUI:
    # ANSI Colors
    RED = "\033[91m"
    GREEN = "\033[92m"
    YELLOW = "\033[93m"
    BLUE = "\033[94m"
    CYAN = "\033[96m"
    RESET = "\033[0m"
    BOLD = "\033[1m"
    DIM = "\033[2m"

    @staticmethod
    def header():
        """起動時のASCIIアート表示"""
        os.system("cls" if os.name == "nt" else "clear")
        logo = r"""
{c}
_____  ______  _    _  __  __           _______   ____  
/ ____||  ____|| |  | ||  \/  |   /\    |__   __| / __ \ 
| (___  | |__   | |  | || \  / |  /  \      | |   | |  | |
\___ \ |  __|  | |  | || |\/| | / /\ \     | |   | |  | |
____) || |     | |__| || |  | |/ ____ \    | |   | |__| |
|_____/ |_|      \____/ |_|  |_/_/    \_\   |_|    \____/ 
{r}{d}  >>> SFUMATO SDR SIMULATOR v1.0 <<<{r}
""".format(c=RadioUI.CYAN, r=RadioUI.RESET, d=RadioUI.DIM)
        print(logo)
        time.sleep(1)

    @staticmethod
    def log(step, message, color=RESET):
        """ステップ実行のログ表示"""
        print(
            f"{RadioUI.DIM}[{time.strftime('%H:%M:%S')}]{RadioUI.RESET} {color}{step:<15}{RadioUI.RESET} : {message}"
        )
        time.sleep(0.3)

    @staticmethod
    def on_air_animation(duration=3):
        """ON AIRの点滅演出"""
        print()
        for _ in range(duration * 2):
            sys.stdout.write(
                f"\r    {RadioUI.RED}{RadioUI.BOLD}● ON AIR{RadioUI.RESET}   Transmitting...  "
            )
            sys.stdout.flush()
            time.sleep(0.5)
            sys.stdout.write(
                f"\r    {RadioUI.DIM}○ ON AIR{RadioUI.RESET}   Transmitting...  "
            )
            sys.stdout.flush()
            time.sleep(0.5)
        print(
            f"\r    {RadioUI.RED}{RadioUI.BOLD}● ON AIR{RadioUI.RESET}   Transmission Stable.    \n"
        )

    @staticmethod
    def tuning_animation():
        """チューニング（選局）演出"""
        print(f"{RadioUI.YELLOW}Scanning Frequencies...{RadioUI.RESET}")
        target_freq = 80.0
        current_freq = 76.0

        while current_freq < target_freq:
            noise_level = random.choice(["▂", "▃", "▅", " ", " "])
            sys.stdout.write(
                f"\r  📻 Tuning... {current_freq:.1f} MHz {RadioUI.DIM}[{noise_level * 5}]{RadioUI.RESET}"
            )
            sys.stdout.flush()
            current_freq += 0.1
            time.sleep(0.05)

        print(
            f"\r  {RadioUI.GREEN}✔ LOCKED SIGNAL{RadioUI.RESET} {target_freq:.1f} MHz {RadioUI.GREEN}[██████]{RadioUI.RESET}    \n"
        )

    @staticmethod
    def signal_meter(snr):
        """信号強度メーターの表示"""
        bars = int(snr / 5)  # 5dBごとに1メモリ
        meter = "█" * bars + "░" * (10 - bars)
        color = (
            RadioUI.GREEN if snr > 20 else (RadioUI.YELLOW if snr > 10 else RadioUI.RED)
        )
        print(f"  Signal Strength: {color}[{meter}]{RadioUI.RESET} SNR: {snr}dB")

    @staticmethod
    def reception_success(filename):
        """受信成功時のレトロなディスプレイ演出"""
        print(
            f"\n{RadioUI.GREEN}{RadioUI.BOLD}   >>> SIGNAL LOCKED! <<<   {RadioUI.RESET}\n"
        )
        time.sleep(0.5)

        # 枠のデザイン
        width = 50
        print(f"{RadioUI.CYAN}╔{'═' * width}╗{RadioUI.RESET}")

        # 1. ステータス表示 (STEREOランプなど)
        status = f"{RadioUI.RED}● STEREO{RadioUI.RESET}   {RadioUI.GREEN}● TUNED{RadioUI.RESET}   {RadioUI.YELLOW}80.0 MHz{RadioUI.RESET}"
        # ANSIエスケープシーケンスを含むので長さ計算を調整して中央寄せ
        padding = 24  # 手動調整 (色の文字数分)
        print(
            f"{RadioUI.CYAN}║{RadioUI.RESET}   {status}      {RadioUI.CYAN}║{RadioUI.RESET}"
        )

        print(f"{RadioUI.CYAN}╠{'─' * width}╣{RadioUI.RESET}")

        # 2. 曲名表示 (Now Playing)
        display_name = os.path.basename(filename)
        if len(display_name) > 30:
            display_name = display_name[:27] + "..."
        print(
            f"{RadioUI.CYAN}║{RadioUI.RESET}  NOW PLAYING: {RadioUI.BOLD}{display_name:<33}{RadioUI.RESET} {RadioUI.CYAN}║{RadioUI.RESET}"
        )

        # 3. ビジュアライザーアニメーション (簡易版)
        print(
            f"{RadioUI.CYAN}║{RadioUI.RESET}                                                  {RadioUI.CYAN}║{RadioUI.RESET}"
        )

        # 5フレームだけ動かす
        bars = [" ", "▂", "▃", "▅", "▆", "▇", "█"]
        for _ in range(6):
            # ランダムな高さのバーを生成
            eq = "".join([random.choice(bars) for _ in range(20)])
            # 両側に配置
            visualizer = f"{RadioUI.GREEN}{eq}{RadioUI.RESET}      {RadioUI.GREEN}{eq}{RadioUI.RESET}"

            sys.stdout.write(
                f"\r{RadioUI.CYAN}║{RadioUI.RESET}   {visualizer}   {RadioUI.CYAN}║{RadioUI.RESET}"
            )
            sys.stdout.flush()
            time.sleep(0.15)

        print(f"\n{RadioUI.CYAN}╚{'═' * width}╝{RadioUI.RESET}")
        print(f"\n{RadioUI.DIM}   File saved to: {filename}{RadioUI.RESET}\n")


# ==========================================
# 🛠 Core Logic (Updated with UI)
# ==========================================


def load_and_preprocess_wav(filename: str, target_fs: int) -> np.ndarray:
    if not os.path.exists(filename):
        raise FileNotFoundError(f"File not found: {filename}")

    RadioUI.log(
        "PREPROCESS", f"Loading '{os.path.basename(filename)}'...", RadioUI.BLUE
    )

    # 1. 読み込み
    data, fs = sf.read(filename)

    # 2. ステレオ -> モノラル変換
    if data.ndim > 1:
        data = data.mean(axis=1)

    # 3. リサンプリング
    if fs != target_fs:
        RadioUI.log("RESAMPLE", f"Converting {fs}Hz -> {target_fs}Hz", RadioUI.CYAN)
        gcd = math.gcd(target_fs, fs)
        up = target_fs // gcd
        down = fs // gcd
        data = signal.resample_poly(data, up, down)

    # 4. 型変換と正規化
    data = data.astype(np.float32)
    max_val = np.abs(data).max()
    if max_val > 1.0:
        data = data / max_val

    return data


def add_awgn_channel(rf_signal: np.ndarray, snr_db: float) -> np.ndarray:
    RadioUI.log("CHANNEL", f"Applying Atmospheric Noise (AWGN)...", RadioUI.YELLOW)
    RadioUI.signal_meter(snr_db)

    signal_power = np.mean(rf_signal**2)
    snr_linear = 10 ** (snr_db / 10)
    noise_power = signal_power / snr_linear
    noise = np.random.normal(0, np.sqrt(noise_power), len(rf_signal))

    return rf_signal + noise


def main():
    # --- UI起動 ---
    RadioUI.header()

    # --- 設定 ---
    INPUT_FILE = "time-tone.wav"
    base_name = os.path.splitext(os.path.basename(INPUT_FILE))[0]
    OUTPUT_FILE = f"outputs/{base_name}_restored.wav"
    TARGET_SNR = 10.0

    # テスト音源生成
    if not os.path.exists(INPUT_FILE):
        RadioUI.log(
            "SYSTEM",
            "Input file missing. Generating Time Signal (Jihō)...",
            RadioUI.YELLOW,
        )
        fs = 44100

        # --- 時報 (Time Signal) 生成ロジック ---
        t_short = np.arange(0, 0.1, 1 / fs)
        beep_440 = 0.5 * np.sin(2 * np.pi * 440 * t_short)

        silence = np.zeros(int(0.9 * fs))

        t_long = np.arange(0, 2.0, 1 / fs)
        beep_880 = 0.5 * np.sin(2 * np.pi * 880 * t_long)

        # 結合: [ピッ+無音] × 3回 + [ポーン]
        unit = np.concatenate([beep_440, silence])
        melody = np.concatenate([unit, unit, unit, beep_880])

        save_audio(melody, fs, INPUT_FILE)

    # --- 1. 送信機 (Transmitter) ---
    print(f"\n{RadioUI.BOLD}--- [1] Transmitter Station ---{RadioUI.RESET}")
    audio_data = load_and_preprocess_wav(INPUT_FILE, settings.AUDIO_FS)

    RadioUI.log("MODULATION", "FM Modulation in progress...", RadioUI.BLUE)
    tx = FmTransmitter()
    rf_signal = tx.modulate(audio_data)

    # 放送開始演出
    RadioUI.on_air_animation(duration=2)

    # --- 2. 通信路 (Channel) ---
    print(f"{RadioUI.BOLD}--- [2] Wireless Channel ---{RadioUI.RESET}")

    # 伝搬遅延演出
    time.sleep(1)
    noisy_rf_signal = add_awgn_channel(rf_signal, TARGET_SNR)
    time.sleep(1)

    # --- 3. 受信機 (Receiver) ---
    print(f"\n{RadioUI.BOLD}--- [3] Receiver Device ---{RadioUI.RESET}")

    # チューニング演出
    RadioUI.tuning_animation()

    RadioUI.log("DEMODULATION", "Quadrature Demodulation...", RadioUI.CYAN)
    rx = FmReceiver()
    demodulated_audio = rx.process(noisy_rf_signal)

    # --- 4. 保存 ---
    print(f"\n{RadioUI.BOLD}--- [4] Output ---{RadioUI.RESET}")
    RadioUI.log("IO", f"Saving audio to {OUTPUT_FILE}", RadioUI.GREEN)
    save_audio(demodulated_audio, rx.audio_fs, OUTPUT_FILE, normalize=False, gain=0.2)

    RadioUI.reception_success(OUTPUT_FILE)


if __name__ == "__main__":
    main()
