# generated by Gemini 3 Pro
import numpy as np
import os
import sys
import time

from sfumato import settings
from sfumato.transmitter import FmTransmitter
from sfumato.reciever import FmReceiver
from sfumato.channnel import add_awgn
from sfumato.component.radio_ui import RadioUI
from sfumato.utils.load_and_preprocess_wav import load_and_preprocess_wav
from sfumato.utils.output_audio import save_audio


def main():
    # --- UI起動 ---
    RadioUI.header()

    # --- 設定 ---
    INPUT_FILE = "time-tone.wav"
    base_name = os.path.splitext(os.path.basename(INPUT_FILE))[0]
    OUTPUT_FILE = f"outputs/{base_name}_restored.wav"
    TARGET_SNR = 10.0

    # テスト音源生成
    if not os.path.exists(INPUT_FILE):
        RadioUI.log(
            "SYSTEM",
            "Input file missing. Generating Time Signal (Jihō)...",
            RadioUI.YELLOW,
        )

        melody = AudioSource.time_tone(fs=44100)
        save_audio(melody, fs, INPUT_FILE)

    # --- 1. 送信機 (Transmitter) ---
    print(f"\n{RadioUI.BOLD}--- [1] Transmitter Station ---{RadioUI.RESET}")
    RadioUI.log(
        "PREPROCESS", f"Loading '{os.path.basename(INPUT_FILE)}'...", RadioUI.BLUE
    )

    audio_data = load_and_preprocess_wav(INPUT_FILE, settings.AUDIO_FS)

    RadioUI.log("CHANNEL", f"Applying Atmospheric Noise (AWGN)...", RadioUI.YELLOW)
    RadioUI.signal_meter(TARGET_SNR)

    RadioUI.log("MODULATION", "FM Modulation in progress...", RadioUI.BLUE)
    tx = FmTransmitter()
    rf_signal = tx.modulate(audio_data)

    # 放送開始演出
    RadioUI.on_air_animation(duration=2)

    # --- 2. 通信路 (Channel) ---
    print(f"{RadioUI.BOLD}--- [2] Wireless Channel ---{RadioUI.RESET}")

    # 伝搬遅延演出
    time.sleep(1)
    noisy_rf_signal = add_awgn(rf_signal, TARGET_SNR)
    time.sleep(1)

    # --- 3. 受信機 (Receiver) ---
    print(f"\n{RadioUI.BOLD}--- [3] Receiver Device ---{RadioUI.RESET}")

    # チューニング演出
    RadioUI.tuning_animation()

    RadioUI.log("DEMODULATION", "Quadrature Demodulation...", RadioUI.CYAN)
    rx = FmReceiver()
    demodulated_audio = rx.process(noisy_rf_signal)

    RadioUI.log(
        "DE-EMP", "Applying 50us De-emphasis (Noise Reduction)...", RadioUI.CYAN
    )

    # --- 4. 保存 ---
    print(f"\n{RadioUI.BOLD}--- [4] Output ---{RadioUI.RESET}")
    RadioUI.log("IO", f"Saving audio to {OUTPUT_FILE}", RadioUI.GREEN)
    save_audio(demodulated_audio, rx.audio_fs, OUTPUT_FILE, normalize=False, gain=0.2)

    RadioUI.reception_success(OUTPUT_FILE)

    # --- 5. グラフ表示 & 保存 ---
    try:
        import matplotlib.pyplot as plt

        RadioUI.log("VISUALIZER", "Generating Analysis Graph...", RadioUI.DIM)

        plt.figure(figsize=(10, 8))  # 少し縦長に見やすく
        limit = 1000

        # 時間領域（波形）の比較
        plt.subplot(2, 1, 1)
        plt.plot(
            audio_data[:limit], label="Original Input (Tx)", alpha=0.7, color="blue"
        )
        plt.plot(
            demodulated_audio[:limit],
            label="Restored Output (Rx)",
            alpha=0.7,
            color="orange",
        )
        plt.title(f"Time Domain Comparison (First {limit} samples)")
        plt.legend(loc="upper right")
        plt.grid(True, linestyle="--", alpha=0.6)
        plt.ylabel("Amplitude")

        # 周波数領域（PSD）の比較
        plt.subplot(2, 1, 2)
        plt.title("Frequency Response Comparison (PSD)")

        # 入力（青）
        plt.psd(
            audio_data,
            Fs=settings.AUDIO_FS,
            NFFT=1024,
            label="Input (Original)",
            color="blue",
            alpha=0.5,
        )
        # 出力（オレンジ）
        plt.psd(
            demodulated_audio,
            Fs=settings.AUDIO_FS,
            NFFT=1024,
            label="Output (Restored)",
            color="orange",
            alpha=0.7,
        )

        plt.legend(loc="upper right")
        plt.xlim(0, 15000)  # 人の声や楽器の主要帯域（0~15kHz）にズーム
        plt.grid(True, linestyle="--", alpha=0.6)

        plt.tight_layout()

        image_filename = f"outputs/{base_name}_analysis.png"
        plt.savefig(image_filename)
        RadioUI.log("IO", f"Graph saved to {image_filename}", RadioUI.GREEN)

        plt.show()

    except Exception as e:
        RadioUI.log("ERROR", f"Graph generation failed: {e}", RadioUI.RED)


if __name__ == "__main__":
    main()
