# generated by Gemini 3 Pro
import numpy as np
import scipy.io.wavfile as wav
import os


def save_audio(
    signal: np.ndarray,
    fs: int,
    filename: str,
    normalize: bool = True,
    gain: float = 0.5,
):
    """
    信号をWAVファイルとして保存するための汎用関数。
    モノラル(1D)とステレオ(2D)の両方に対応

    Args:
        signal (np.ndarray): 音声信号。Shapeは (N,) または (N, 2)
        fs (int): サンプリング周波数
        filename (str): 保存先のパス
        normalize (bool): Trueならピークを gain に合わせる。
                          ステレオの場合、左右のバランス（定位）を保ったまま正規化
        gain (float): 音量の目標値 (0.0 〜 1.0)。
    """

    audio_data = signal.copy()

    # モノラル/ステレオの判定 (ログ出力用)
    channels = 1
    if audio_data.ndim == 2:
        channels = audio_data.shape[1]

    mode_str = "Stereo" if channels == 2 else "Mono"

    # 1. DCオフセット除去
    audio_data = audio_data - np.mean(audio_data, axis=0)

    # 2. 音量調整
    if normalize:
        # ステレオの場合、全体の最大値で割ることで、左右の音量差（パンニング）を維持します
        max_val = np.max(np.abs(audio_data))
        if max_val > 0:
            audio_data = (audio_data / max_val) * gain
    else:
        audio_data = audio_data * gain

    # 3. float32 から int16 に変換 (クリッピング防止付き)
    # -1.0〜1.0 に収める
    audio_data = np.clip(audio_data, -1.0, 1.0)
    audio_int16 = (audio_data * 32767).astype(np.int16)

    os.makedirs(
        os.path.dirname(filename) if os.path.dirname(filename) else ".", exist_ok=True
    )
    wav.write(filename, int(fs), audio_int16)
    print(f"Saved [{mode_str}] audio to: {filename} (Gain: {gain})")
