# generated by Gemini 3 Pro
# ==========================================
# 🎨 Radio UI System
# ==========================================
import os
import sys
import time
import random


class RadioUI:
    # ANSI Colors
    RED = "\033[91m"
    GREEN = "\033[92m"
    YELLOW = "\033[93m"
    BLUE = "\033[94m"
    CYAN = "\033[96m"
    RESET = "\033[0m"
    BOLD = "\033[1m"
    DIM = "\033[2m"

    @staticmethod
    def header():
        """起動時のASCIIアート表示"""
        os.system("cls" if os.name == "nt" else "clear")
        logo = r"""
{c}
_____  ______  _    _  __  __           _______   ____  
/ ____||  ____|| |  | ||  \/  |   /\    |__   __| / __ \ 
| (___  | |__   | |  | || \  / |  /  \      | |   | |  | |
\___ \ |  __|  | |  | || |\/| | / /\ \     | |   | |  | |
____) || |     | |__| || |  | |/ ____ \    | |   | |__| |
|_____/ |_|      \____/ |_|  |_/_/    \_\   |_|    \____/ 
{r}{d}  >>> SFUMATO SDR SIMULATOR v1.0 <<<{r}
""".format(c=RadioUI.CYAN, r=RadioUI.RESET, d=RadioUI.DIM)
        print(logo)
        time.sleep(1)

    @staticmethod
    def log(step, message, color=RESET):
        """ステップ実行のログ表示"""
        print(
            f"{RadioUI.DIM}[{time.strftime('%H:%M:%S')}]{RadioUI.RESET} {color}{step:<15}{RadioUI.RESET} : {message}"
        )
        time.sleep(0.3)

    @staticmethod
    def on_air_animation(duration=3):
        """ON AIRの点滅演出"""
        print()
        for _ in range(duration * 2):
            sys.stdout.write(
                f"\r    {RadioUI.RED}{RadioUI.BOLD}● ON AIR{RadioUI.RESET}   Transmitting...  "
            )
            sys.stdout.flush()
            time.sleep(0.5)
            sys.stdout.write(
                f"\r    {RadioUI.DIM}○ ON AIR{RadioUI.RESET}   Transmitting...  "
            )
            sys.stdout.flush()
            time.sleep(0.5)
        print(
            f"\r    {RadioUI.RED}{RadioUI.BOLD}● ON AIR{RadioUI.RESET}   Transmission Stable.    \n"
        )

    @staticmethod
    def tuning_animation():
        """チューニング（選局）演出"""
        print(f"{RadioUI.YELLOW}Scanning Frequencies...{RadioUI.RESET}")
        target_freq = 80.0
        current_freq = 76.0

        while current_freq < target_freq:
            noise_level = random.choice(["▂", "▃", "▅", " ", " "])
            sys.stdout.write(
                f"\r  📻 Tuning... {current_freq:.1f} MHz {RadioUI.DIM}[{noise_level * 5}]{RadioUI.RESET}"
            )
            sys.stdout.flush()
            current_freq += 0.1
            time.sleep(0.05)

        print(
            f"\r  {RadioUI.GREEN}✔ LOCKED SIGNAL{RadioUI.RESET} {target_freq:.1f} MHz {RadioUI.GREEN}[██████]{RadioUI.RESET}    \n"
        )

    @staticmethod
    def signal_meter(snr):
        """信号強度メーターの表示"""
        bars = int(snr / 5)  # 5dBごとに1メモリ
        meter = "█" * bars + "░" * (10 - bars)
        color = (
            RadioUI.GREEN if snr > 20 else (RadioUI.YELLOW if snr > 10 else RadioUI.RED)
        )
        print(f"  Signal Strength: {color}[{meter}]{RadioUI.RESET} SNR: {snr}dB")

    @staticmethod
    def reception_success(filename):
        """受信成功時のレトロなディスプレイ演出"""
        print(
            f"\n{RadioUI.GREEN}{RadioUI.BOLD}   >>> SIGNAL LOCKED! <<<   {RadioUI.RESET}\n"
        )
        time.sleep(0.5)

        # 枠のデザイン
        width = 50
        print(f"{RadioUI.CYAN}╔{'═' * width}╗{RadioUI.RESET}")

        # 1. ステータス表示 (STEREOランプなど)
        status = f"{RadioUI.RED}● STEREO{RadioUI.RESET}   {RadioUI.GREEN}● TUNED{RadioUI.RESET}   {RadioUI.YELLOW}80.0 MHz{RadioUI.RESET}"
        # ANSIエスケープシーケンスを含むので長さ計算を調整して中央寄せ
        padding = 24  # 手動調整 (色の文字数分)
        print(
            f"{RadioUI.CYAN}║{RadioUI.RESET}   {status}      {RadioUI.CYAN}║{RadioUI.RESET}"
        )

        print(f"{RadioUI.CYAN}╠{'─' * width}╣{RadioUI.RESET}")

        # 2. 曲名表示 (Now Playing)
        display_name = os.path.basename(filename)
        if len(display_name) > 30:
            display_name = display_name[:27] + "..."
        print(
            f"{RadioUI.CYAN}║{RadioUI.RESET}  NOW PLAYING: {RadioUI.BOLD}{display_name:<33}{RadioUI.RESET} {RadioUI.CYAN}║{RadioUI.RESET}"
        )

        # 3. ビジュアライザーアニメーション
        print(
            f"{RadioUI.CYAN}║{RadioUI.RESET}                                                  {RadioUI.CYAN}║{RadioUI.RESET}"
        )

        # 5フレームだけ動かす
        bars = [" ", "▂", "▃", "▅", "▆", "▇", "█"]
        for _ in range(6):
            # ランダムな高さのバーを生成
            eq = "".join([random.choice(bars) for _ in range(20)])
            # 両側に配置
            visualizer = f"{RadioUI.GREEN}{eq}{RadioUI.RESET}      {RadioUI.GREEN}{eq}{RadioUI.RESET}"

            sys.stdout.write(
                f"\r{RadioUI.CYAN}║{RadioUI.RESET}   {visualizer}   {RadioUI.CYAN}║{RadioUI.RESET}"
            )
            sys.stdout.flush()
            time.sleep(0.15)

        print(f"\n{RadioUI.CYAN}╚{'═' * width}╝{RadioUI.RESET}")
        print(f"\n{RadioUI.DIM}   File saved to: {filename}{RadioUI.RESET}\n")
