# generated by Gemini 3 Pro
import os
import math
import numpy as np
import soundfile as sf
from scipy import signal


def load_and_preprocess_wav(
    filename: str,
    target_fs: int,
    to_mono: bool = False,
    normalize_peak: float = 0.98,
) -> np.ndarray:
    """
    WAVファイルを読み込み、リサンプリング・正規化を行う。

    Args:
        filename: ファイルパス
        target_fs: 目標サンプリング周波数
        mono: Trueなら強制的にモノラル化、Falseなら元のチャンネル数を維持

    Returns:
        np.ndarray: 音声データ (N,) または (N, 2)
    """
    if not os.path.exists(filename):
        raise FileNotFoundError(f"File not found: {filename}")

    data, fs = sf.read(filename)

    if to_mono:
        if data.ndim > 1:
            data = data.mean(axis=1)
    else:
        if data.ndim == 1:
            data = np.column_stack([data, data])

    if fs != target_fs:
        gcd = math.gcd(target_fs, fs)
        up = target_fs // gcd
        down = fs // gcd
        data = signal.resample_poly(data, up, down)

    data = data.astype(np.float32)

    max_val = np.max(np.abs(data))
    if max_val > 0:
        data = data * (normalize_peak / max_val)

    return data
