# generated by Gemini 3 Pro
import numpy as np
import scipy.io.wavfile as wav
import os


def save_audio(
    signal: np.ndarray,
    fs: int,
    filename: str,
    normalize: bool = True,
    gain: float = 0.5,
):
    """
    信号をWAVファイルとして保存するための汎用関数。

    Args:
        signal (np.ndarray): 保存したい音声信号
        fs (int): サンプリング周波数
        filename (str): 保存先のパス
        normalize (bool): Trueならピークを gain に合わせる。Falseならそのまま保存。
        gain (float): 音量の目標値 (0.0 〜 1.0)。デフォルトは 0.5 (50%)。
                      normalize=True の場合は「最大音量」、Falseの場合は「単純な倍率」になります。
    """

    audio_data = signal.copy()

    # 1. DCオフセット除去
    audio_data = audio_data - np.mean(audio_data)

    # 2. 音量調整
    if normalize:
        max_val = np.max(np.abs(audio_data))
        if max_val > 0:
            audio_data = (audio_data / max_val) * gain
    else:
        audio_data = audio_data * gain

    # 3. float32 から int16 に変換 (クリッピング防止付き)
    # 1.0 を超えると音が割れるので、念のため -1.0〜1.0 に収める
    audio_data = np.clip(audio_data, -1.0, 1.0)
    audio_int16 = (audio_data * 32767).astype(np.int16)

    os.makedirs(
        os.path.dirname(filename) if os.path.dirname(filename) else ".", exist_ok=True
    )
    wav.write(filename, int(fs), audio_int16)
    print(f"Saved audio to: {filename} (Gain: {gain})")
